ftp:
    localhost:
        username: 
        password: 
shareonlinebiz:
    username:
    password:
uploadednet:
    username: 
    password: 
rapidgatornet:
    username: 
    password: 
dropboxcom:
    token: 